version: "2"

services:

  sonarqube:
    image: ${NS}/demo-sonarqube-postgresql-ktadvance:${TAG}
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data${TAG}
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    depends_on:
      - db


  db:
    image: ${NS}/postgresql-empty-sq:${TAG}
    networks:
      - sonarnet
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql/db-${TAG}
      - postgresql_data:/var/lib/postgresql/db-${TAG}/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
