#!/bin/bash
TAG=$SOURCE_BRANCH


echo "SOURCE_BRANCH=$SOURCE_BRANCH"
echo "DOCKER_REPO=$DOCKER_REPO"
echo "CACHE_TAG=$CACHE_TAG"
echo "NS=$NS"
echo "TAG=$TAG"
echo "------------------------"
docker build --no-cache --build-arg CACHE_TAG=$TAG --build-arg NS=$NS -f $DOCKERFILE_PATH -t $IMAGE_NAME .
